import Head from 'next/head';
import { Header } from '@/components/global/Header';
import Topbar from '@/components/global/Topbar';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header title="Home" subtitle="Bem vindo" />
        <h1>oi</h1>
      </main>
    </>
  );
}
